[package]
name = "starknet-core"
version = "0.3.2"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/xJonathanLEI/starknet-rs"
homepage = "https://starknet.rs/"
description = """
Core structures for the starknet crate
"""
keywords = ["ethereum", "starknet", "web3"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
starknet-crypto = { version = "0.5.1", path = "../starknet-crypto", default-features = false }
starknet-ff = { version = "0.3.3", path = "../starknet-ff", default-features = false, features = [
    "serde",
] }
base64 = { version = "0.21.0", default-features = false, features = ["alloc"] }
ethereum-types = { version = "0.14.1", default-features = false, features = ["serialize"] }
flate2 = { version = "1.0.25", optional = true }
hex = { version = "0.4.3", default-features = false }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.96", default-features = false, features = ["arbitrary_precision", "alloc"]}
serde_with = { version = "2.3.2", default-features = false, features = ["macros", "alloc"] }
sha3 = { version = "0.10.7", default-features = false }
thiserror = { version = "1.0.40", default-features = false }
thiserror-no-std = { version = "2.0.2" }

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }
starknet-core = { path = ".", features = ["no_unknown_fields"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3.34", default-features = false }

[features]
default = ["std", "bigdecimal", "compression"]
std = ["serde_json/std"]
bigdecimal = ["starknet-ff/bigdecimal", "starknet-crypto/bigdecimal"]
no_unknown_fields = []
compression = ["std", "dep:flate2"]

[[bench]]
name = "class_hash"
harness = false
